### ISSUE TITLE
google.protobuf.Empty as param

### ISSUE THREAD

**Issue by n0mer** [grpc-ecosystem/polyglot#105]
hello, my gRPC method accepts `google.probuf.Empty`

What should i provide in `echo <json>` part in order to avoid `java.lang.IllegalArgumentException: Can't make call without any requests`: 

```
[main] WARN me.dinowernli.grpc.polyglot.Main - Caught top-level exception during command execution
java.lang.RuntimeException: Caught exception while waiting for rpc
	at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:113)
	at me.dinowernli.grpc.polyglot.Main.main(Main.java:70)
Caused by: java.lang.IllegalArgumentException: Can't make call without any requests
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at me.dinowernli.grpc.polyglot.grpc.DynamicGrpcClient.call(DynamicGrpcClient.java:45)
	at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:111)
	... 1 more
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Caught exception while waiting for rpc
	at me.dinowernli.grpc.polyglot.Main.main(Main.java:86)
Caused by: java.lang.RuntimeException: Caught exception while waiting for rpc
	at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:113)
	at me.dinowernli.grpc.polyglot.Main.main(Main.java:70)
Caused by: java.lang.IllegalArgumentException: Can't make call without any requests
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at me.dinowernli.grpc.polyglot.grpc.DynamicGrpcClient.call(DynamicGrpcClient.java:45)
	at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:111)
	... 1 more
```

**Comment by n0mer** [comment]
```bash
echo {} | java ...
```
works fine.
