### ISSUE TITLE
Support building binaries which run on Mac

### ISSUE THREAD

**Issue by dinowernli** [grpc-ecosystem/polyglot#20]

**Comment by mwitkow** [comment]
Bazel 0.2.0:

```
michal:~/code/polyglot/ (master) $ bazel build ...                             [14:03:35]
zsh: correct '...' to '..' [nyae]? n
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
SLF4J: org.eclipse.aether.internal.impl.DefaultRepositorySystem
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@tcnative_boringssl_static_linux_x86_64' (requested by nodes 'REPOSITORY:@tcnative_boringssl_static_linux_x86_64')
INFO: Elapsed time: 12.792s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@tcnative_boringssl_static_linux_x86_64' (requested by nodes 'REPOSITORY:@tcnative_boringssl_static_linux_x86_64')
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
    at com.google.common.io.ByteStreams.copy(ByteStreams.java:105)
    at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:168)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader$HttpConnection.createAndConnect(HttpDownloader.java:248)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:126)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:88)
    at com.google.devtools.build.lib.bazel.repository.HttpArchiveFunction.fetch(HttpArchiveFunction.java:61)
    at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:124)
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
    ... 4 more
```

**Comment by mwitkow** [comment]
On the build mac and windows branch:

```
michal:~/code/polyglot/ (build-for-mac-and-win) $ bazel build ...                                                                                        [14:10:37]
zsh: correct '...' to '..' [nyae]? n
......
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@protoc_linux_x86_64' (requested by nodes 'REPOSITORY:@protoc_linux_x86_64')
INFO: Elapsed time: 1.227s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@protoc_linux_x86_64' (requested by nodes 'REPOSITORY:@protoc_linux_x86_64')
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
    at com.google.common.io.ByteStreams.copy(ByteStreams.java:105)
    at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:168)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader$HttpConnection.createAndConnect(HttpDownloader.java:248)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:126)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:88)
    at com.google.devtools.build.lib.bazel.repository.HttpArchiveFunction.fetch(HttpArchiveFunction.java:61)
    at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:124)
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
    ... 4 more
michal:~/code/polyglot/ (build-for-mac-and-win) $ bazel build ... --cpu=darwin_x86_64                                                                    [14:10:44]
zsh: correct '...' to '..' [nyae]? n
......
Unhandled exception thrown during build; message: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@tcnative_boringssl_static_linux_x86_64' (requested by nodes 'REPOSITORY:@tcnative_boringssl_static_linux_x86_64')
INFO: Elapsed time: 0.715s
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@tcnative_boringssl_static_linux_x86_64' (requested by nodes 'REPOSITORY:@tcnative_boringssl_static_linux_x86_64')
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:1003)
    at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:212)
    at com.google.common.io.ByteStreams.copy(ByteStreams.java:105)
    at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:168)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader$HttpConnection.createAndConnect(HttpDownloader.java:248)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:126)
    at com.google.devtools.build.lib.bazel.repository.HttpDownloader.download(HttpDownloader.java:88)
    at com.google.devtools.build.lib.bazel.repository.HttpArchiveFunction.fetch(HttpArchiveFunction.java:61)
    at com.google.devtools.build.lib.rules.repository.RepositoryDelegatorFunction.compute(RepositoryDelegatorFunction.java:124)
    at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:954)
    ... 4 more
```

**Comment by dinowernli** [comment]
This is fixed with https://github.com/dinowernli/polyglot/pull/23.
