### ISSUE TITLE
How to supply raw byte data?

### ISSUE THREAD

**Issue by anopheles** [grpc-ecosystem/polyglot#49]
I have following (incomplete) protobuf definition
```
message Create {
   bytes data = 1;
}
```

How do I create a json request with polyglot that sets the parameter.
```
data=$(base64 image.jpeg)
echo '{"data" : "'$data'" }' | call --full_method=Create
```
doens't seem to work.

```
[main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.2.0+dev
[main] INFO me.dinowernli.grpc.polyglot.Main - Loaded configuration: 
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating dynamic grpc client
[main] INFO io.grpc.internal.ManagedChannelImpl - [ManagedChannelImpl@448ff1a8] Created with target localhost:8182
Exception in thread "main" java.lang.RuntimeException: Caught exception during command execution
	at me.dinowernli.grpc.polyglot.Main.main(Main.java:87)
Caused by: java.lang.IllegalArgumentException: Unable to read messages from: STDIN
	at me.dinowernli.grpc.polyglot.io.MessageReader.read(MessageReader.java:85)
	at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:75)
	at me.dinowernli.grpc.polyglot.Main.main(Main.java:72)
Caused by: com.google.protobuf.InvalidProtocolBufferException: com.google.common.io.BaseEncoding$DecodingException: Unrecognized character: 0x20
	at com.google.protobuf.util.JsonFormat$ParserImpl.merge(JsonFormat.java:992)
	at com.google.protobuf.util.JsonFormat$Parser.merge(JsonFormat.java:231)
	at me.dinowernli.grpc.polyglot.io.MessageReader.read(MessageReader.java:79)
```

**Comment by dinowernli** [comment]
Hi @anopheles 

I've taken a look at the grpc json parser code and it seems that in order to use bytes inside the json textformat, you are going to have to base64-encode your bytes [1]. Does this help?

Cheers
Dino

[1] https://github.com/google/protobuf/blob/master/java/util/src/main/java/com/google/protobuf/util/JsonFormat.java#L994

**Comment by dinowernli** [comment]
Closing this up, please reopen if you are still seeing issues.
