### ISSUE TITLE
polyglot jar not including Well Known Types for protos

### ISSUE THREAD

**Issue by stevededalus** [grpc-ecosystem/polyglot#73]
The released jar for polyglot is not working with well known types for protos (i.e. timestamps).

`protoc` run locally works fine and the well known types are present in `/usr/local/include/google/protobuf/`

```
Michaels-MacBook-Pro:idls sindelar$ java -jar polyglot.jar --command=list_services --proto_discovery_root=model/
[main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.3.0
[main] INFO me.dinowernli.grpc.polyglot.Main - Loaded configuration:
google/protobuf/timestamp.proto: File not found.
replica.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.
replica.proto:120:3: "google.protobuf.Timestamp" is not defined.
replica.proto:122:3: "google.protobuf.Timestamp" is not defined.
replica.proto:145:3: "google.protobuf.Timestamp" is not defined.
replica.proto:146:3: "google.protobuf.Timestamp" is not defined.
[main] WARN me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker - Protoc invocation failed with status: 1
[main] WARN me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker - [Protoc log] protoc-jar: protoc version: 300, detected platform: mac os x/x86_64
[main] WARN me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker - [Protoc log] protoc-jar: executing: [/var/folders/xz/ytdp_wr52cj2jhxz76_m6b6w0000gn/T/protoc4924784953496390184.exe, /Users/sindelar/sidewalk/idls/model/replica.proto, /Users/sindelar/sidewalk/idls/model/map_service.proto, /Users/sindelar/sidewalk/idls/model/persona.proto, -I/Users/sindelar/sidewalk/idls/model, --descriptor_set_out=/var/folders/xz/ytdp_wr52cj2jhxz76_m6b6w0000gn/T/descriptor904114720190676395.pb.bin, --include_imports]
Exception in thread "main" java.lang.RuntimeException: Failed to invoke the protoc binary
	at me.dinowernli.grpc.polyglot.Main.getFileDescriptorSet(Main.java:96)
	at me.dinowernli.grpc.polyglot.Main.main(Main.java:52)
Caused by: me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker$ProtocInvocationException: Got exit code [1] from protoc with args [[/Users/sindelar/sidewalk/idls/model/replica.proto, /Users/sindelar/sidewalk/idls/model/map_service.proto, /Users/sindelar/sidewalk/idls/model/persona.proto, -I/Users/sindelar/sidewalk/idls/model, --descriptor_set_out=/var/folders/xz/ytdp_wr52cj2jhxz76_m6b6w0000gn/T/descriptor904114720190676395.pb.bin, --include_imports]]
	at me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker.invokeBinary(ProtocInvoker.java:132)
	at me.dinowernli.grpc.polyglot.protobuf.ProtocInvoker.invoke(ProtocInvoker.java:82)
	at me.dinowernli.grpc.polyglot.Main.getFileDescriptorSet(Main.java:94)
	... 1 more
```

Seems related to this issue
https://github.com/google/protobuf/issues/1889

**Comment by xiaogaozi** [comment]
You can use `--add_protoc_includes=/usr/local/include` this option as a workaround.

**Comment by thurt** [comment]
adding to @xiaogaozi, you can also include multiple paths by separating with a comma
```
--add_protoc_includes=/user/local/include,/some/other/path
```
