### ISSUE TITLE
When polyglot exits due to error the exit status is 0

### ISSUE THREAD

**Issue by edmund-troche** [grpc-ecosystem/polyglot#77]
I've run `polyglot` a few times to list services or call procedures and every time it returns after a stack trace or some error the process always exists with status code 0. It would be useful if it could return with a non-zero value for the cases where it fails to perform the given operation. Of course there is also the case where we make a call to a procedure (command=call) and the RPC itself returns an error. I think in this last case it would be nice to have another flag added to `polyglot` where we can specify what process exit code we want it to return when the RPC itself returns with error, e.g. `--rpc_err_exit_code=1` would mean "have the `polyglot` process exit with code 1 if RPC error != null`.

**Comment by dinowernli** [comment]
@edmund-troche In PR https://github.com/grpc-ecosystem/polyglot/pull/78 I am fixing the case where failure to parse command line flags would mistakenly exit with 0.

As far as I can tell, the other cases where exceptions bubble up to top level should result in error code 1. Do you think you could post the output of an example execution which exhibits the problem you are describing?

**Comment by edmund-troche** [comment]
@dinowernli, here is one example where I'm doing a `call` and the server is not reachable:
```console
$ ./get_key.sh
[main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.4.0
[main] INFO me.dinowernli.grpc.polyglot.Main - Loaded configuration:
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating channel to: localhost:xxxx
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Using proto descriptors obtained from protoc
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating dynamic grpc client
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Making rpc with 1 request(s) to endpoint [localhost:xxxx]
[main] INFO me.dinowernli.grpc.polyglot.grpc.DynamicGrpcClient - Making unary call
[grpc-default-executor-1] ERROR me.dinowernli.grpc.polyglot.io.LoggingStatsWriter - Aborted rpc due to error
io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.Status.asRuntimeException(Status.java:543)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:xxxx
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
Caused by: java.net.ConnectException: Connection refused
	... 11 more
✔ ~/go/src/xxxxx/test [develop ↓·1↑·11|✚ 3…18]
08:21 $ echo $?
0
```

This is an example where I make a `call` and the rpc returns an error:
```console
$ ./get_key.sh
[main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.4.0
[main] INFO me.dinowernli.grpc.polyglot.Main - Loaded configuration:
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating channel to: localhost:xxxx
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Using proto descriptors obtained from protoc
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating dynamic grpc client
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Making rpc with 1 request(s) to endpoint [localhost:xxxx]
[main] INFO me.dinowernli.grpc.polyglot.grpc.DynamicGrpcClient - Making unary call
[grpc-default-executor-0] ERROR me.dinowernli.grpc.polyglot.io.LoggingStatsWriter - Aborted rpc due to error
io.grpc.StatusRuntimeException: UNKNOWN: rpc processing failed
	at io.grpc.Status.asRuntimeException(Status.java:543)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:442)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
✔ ~/go/src/xxxx/test [develop ↓·1↑·11|✚ 3…18]
08:30 $ echo $?
0
```

These are two cases I know of, there may be others, hopefully this is helpful. 

Thanks

**Comment by edmund-troche** [comment]
@dinowernli one more thing, I'm running with the prebuilt JAR from the last release.

**Comment by dinowernli** [comment]
@edmund-troche thanks a lot for the examples, these are both cases where the rpc itself fails (rather than the setup or the parsing).

In in https://github.com/grpc-ecosystem/polyglot/pull/81 I have made sure that Polyglot returns a non-zero exit code if the rpc fails. I would rather wait with making the error code configurable until we know that there is really a need for it.

**Comment by edmund-troche** [comment]
@dinowernli Thanks for the code change in #81.

I wanted to clarify the need for a configurable exit code. More than the configurability aspect, what would be useful is to be able to distinguish when the error is due to a failed gRPC request vs some other error (e.g. error on how `polyglot` was called, or input payload parsing, etc). So, this could be easily addressed by just returning some other exit code for the case where the gRPC fails. There may be room for returning other exit codes under other scenarios, for example, if the gRPC failed because it could not connect to the service (e.g. target service is not running, or not reachable), maybe return exit code "2", if we can connect to the service and it fails due to other errors then exit  with some of other code. Anyway, I'm thinking about how I would use `polyglot` for some simple automated tests, I would not want the test code to assume that some gRPC code broke when in fact it is one of those other cases, like an error on how polyglot was called, or the payload, or the service is still not up and running, etc.
