### ISSUE TITLE
Cope with TLS client keys in PKCS#1 format

### ISSUE THREAD

**Issue by hatstand** [grpc-ecosystem/polyglot#85]
If you try to connect with `--tls_client_key_path` point to a valid private key in PKCS#1 format, Polyglot dies with:

```
java.lang.IllegalArgumentException: File does not contain valid private key: out/polyglot.key
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:222)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createSslContext(ChannelFactory.java:105)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:71)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannel(ChannelFactory.java:51)
        at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:68)
        at me.dinowernli.grpc.polyglot.Main.main(Main.java:70)
Caused by: java.security.NoSuchAlgorithmException: EC KeyFactory not available
        at java.security.KeyFactory.<init>(java.base@9-internal/KeyFactory.java:138)
        at java.security.KeyFactory.getInstance(java.base@9-internal/KeyFactory.java:179)
        at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1043)
        at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
        ... 6 more
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: File does not contain valid private key: out/polyglot.key
        at me.dinowernli.grpc.polyglot.Main.main(Main.java:86)
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: out/polyglot.key
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:222)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createSslContext(ChannelFactory.java:105)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:71)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannel(ChannelFactory.java:51)
        at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:68)
        at me.dinowernli.grpc.polyglot.Main.main(Main.java:70)
Caused by: java.security.NoSuchAlgorithmException: EC KeyFactory not available
        at java.security.KeyFactory.<init>(java.base@9-internal/KeyFactory.java:138)
        at java.security.KeyFactory.getInstance(java.base@9-internal/KeyFactory.java:179)
        at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1043)
        at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
        ... 6 more
```

Converting the key with this command line makes it work:

```openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in polyglot.key -out polyglot-pkcs8.key```

Would be nice if Polyglot figured this out on its own or at least told you what the issue is.

**Comment by dinowernli** [comment]
Thanks a lot for reporting this. It looks like Netty only support PKCS8: https://netty.io/wiki/sslcontextbuilder-and-private-key.html

Judging from how similar your command is to the command described on the page, you probably found that page as well ;-)

I suspect that for now, catching the exception and printing the link (or the command) might be the right thing to do. Will put together a PR.

**Comment by dinowernli** [comment]
@hatstand I have a tentative PR up (see above). Is there any chance you could try that branch and see if the custom error message actually triggers? it should point to here, where you have left your helpful command.

**Comment by hatstand** [comment]
The PR fixes it for Java 9 but not Java 8:
```
[main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.6.0+dev
[main] INFO me.dinowernli.grpc.polyglot.Main - Loaded configuration:
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating channel to: 192.168.111.66:5001 [main] WARN me.dinowernli.grpc.polyglot.Main - Caught top-level exception during command execution
java.lang.IllegalArgumentException: File does not contain valid private key: /home/john/out/polyglot.key
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:222)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createSslContext(ChannelFactory.java:110)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:72)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannel(ChannelFactory.java:52)
        at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:68)
        at me.dinowernli.grpc.polyglot.Main.main(Main.java:70)
Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
        at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1045)
        at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
        ... 6 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
        at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:169)
        at java.security.KeyFactory.generatePrivate(KeyFactory.java:372)
        at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1043)
        ... 8 more
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:352)
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:357)
        at sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:73)
        at sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237)
        at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165)
        ... 10 more
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: File does not contain valid private key: /home/john/out/polyglot.key
        at me.dinowernli.grpc.polyglot.Main.main(Main.java:86)
Caused by: java.lang.IllegalArgumentException: File does not contain valid private key: /home/john/out/polyglot.key
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:267)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:222)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createSslContext(ChannelFactory.java:110)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannelBuilder(ChannelFactory.java:72)
        at me.dinowernli.grpc.polyglot.grpc.ChannelFactory.createChannel(ChannelFactory.java:52)
        at me.dinowernli.grpc.polyglot.command.ServiceCall.callEndpoint(ServiceCall.java:68)
        at me.dinowernli.grpc.polyglot.Main.main(Main.java:70)
Caused by: java.security.spec.InvalidKeySpecException: Neither RSA, DSA nor EC worked
        at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1045)
        at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1014)
        at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:265)
        ... 6 more
Caused by: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
        at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:169)
        at java.security.KeyFactory.generatePrivate(KeyFactory.java:372)
        at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1043)
        ... 8 more
Caused by: java.security.InvalidKeyException: IOException : algid parse error, not a sequence
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:352)
        at sun.security.pkcs.PKCS8Key.decode(PKCS8Key.java:357)
        at sun.security.ec.ECPrivateKeyImpl.<init>(ECPrivateKeyImpl.java:73)
        at sun.security.ec.ECKeyFactory.implGeneratePrivate(ECKeyFactory.java:237)
        at sun.security.ec.ECKeyFactory.engineGeneratePrivate(ECKeyFactory.java:165)
        ... 10 more
```

**Comment by dinowernli** [comment]
PR https://github.com/grpc-ecosystem/polyglot/pull/87 fixes this for both java 8 and java 9.

**Comment by bernardgonzales** [comment]
Thank you for sharing your fix!
