### ISSUE TITLE
Server Reflection not used

### ISSUE THREAD

**Issue by domgreen** [grpc-ecosystem/polyglot#93]
When using `Polyglot 1.6.0` it doesnt seem to trigger server reflection and always falls back to `protoc` this example is using the HelloWorld example from the go-grpc.

Server code with reflection: https://github.com/grpc/grpc-go/blob/master/examples/helloworld/greeter_server/main.go

Call:
```
echo {'name':'dom'} | java -jar ~/polyglot.jar \
--command=call \
--use_reflection=true --endpoint=localhost:50051 \
--full_method=helloworld.Greeter/SayHello \
--proto_discovery_root=.
```

Output:
```
[main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.6.0
[main] INFO me.dinowernli.grpc.polyglot.Main - Loaded configuration:
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating channel to: localhost:50051
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Using proto descriptors obtained from protoc
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating dynamic grpc client
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Making rpc with 1 request(s) to endpoint [localhost:50051]
[main] INFO me.dinowernli.grpc.polyglot.grpc.DynamicGrpcClient - Making unary call
[grpc-default-executor-0] INFO me.dinowernli.grpc.polyglot.io.LoggingStatsWriter - Got response message
{
  "message": "Hello dom"
}

[grpc-default-executor-0] INFO me.dinowernli.grpc.polyglot.io.LoggingStatsWriter - Completed rpc with 1 response(s)
```

**Comment by dinowernli** [comment]
@domgreen I have just tried, first from head, then with the exact version 1.6.0, but I cannot reproduce the bug [1]. Any chance you could run an instrumented polyglot from source and log the following:
* Verify that this branch [2] is getting triggered by logging something.
* Logging any exceptions that happen here [3].

Also, in your log above, how did polyglot actually get the schema? Did you feed it the actual proto files?


[1]
```
echo {'name':'dom'} | java -jar ~/Downloads/polyglot-1.6.0.jar \
--command=call \
--use_reflection=true --endpoint=localhost:50051 \
--full_method=helloworld.Greeter/SayHello \
--proto_discovery_root=.
[main] INFO me.dinowernli.grpc.polyglot.Main - Polyglot version: 1.6.0
[main] INFO me.dinowernli.grpc.polyglot.Main - Loaded configuration:
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating channel to: localhost:50051
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/Users/dino/Downloads/polyglot-1.6.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Using proto descriptors fetched by reflection
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Creating dynamic grpc client
[main] INFO me.dinowernli.grpc.polyglot.command.ServiceCall - Making rpc with 1 request(s) to endpoint [localhost:50051]
[main] INFO me.dinowernli.grpc.polyglot.grpc.DynamicGrpcClient - Making unary call
[grpc-default-executor-1] INFO me.dinowernli.grpc.polyglot.io.LoggingStatsWriter - Got response message
{
  "message": "Hello dom"
}

[grpc-default-executor-1] INFO me.dinowernli.grpc.polyglot.io.LoggingStatsWriter - Completed rpc with 1 response(s)
```

[2] https://github.com/grpc-ecosystem/polyglot/blob/master/src/main/java/me/dinowernli/grpc/polyglot/command/ServiceCall.java#L76

[3] https://github.com/grpc-ecosystem/polyglot/blob/master/src/main/java/me/dinowernli/grpc/polyglot/command/ServiceCall.java#L130

**Comment by Zyanbo** [comment]
hello，invoking ServerReflectionClient.listServices() Method errors，
What is the reason for this?

Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error in server reflection rpc while listing services
	at io.grpc.grpcswagger.utils.GrpcReflectionUtils.resolveService(GrpcReflectionUtils.java:77)
	at io.grpc.grpcswagger.service.GrpcProxyService.invokeMethod(GrpcProxyService.java:30)
	at io.grpc.grpcswagger.service.Test.run(Test.java:76)
	at io.grpc.grpcswagger.service.Test.main(Test.java:28)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error in server reflection rpc while listing services
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:528)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:509)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:85)
	at io.grpc.grpcswagger.utils.GrpcReflectionUtils.resolveService(GrpcReflectionUtils.java:67)
	... 3 more
Caused by: java.lang.RuntimeException: Error in server reflection rpc while listing services
	at io.grpc.grpcswagger.grpc.ServerReflectionClient$ListServicesHandler.onError(ServerReflectionClient.java:98)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:434)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:678)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:397)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: DEADLINE_EXCEEDED: deadline exceeded after 888505520ns
	at io.grpc.Status.asRuntimeException(Status.java:526)
	... 19 more
